image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
- port: 3000

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
  # init runs during prebuild
- init: >
    python3 -m pip install https://codeload.github.com/dwavesystems/dwave-cloud-client/zip/master ;
    (cd pipelines; python3 -m pip install -r requirements.txt);
  #
  command: (cd pipelines; python3 pipelines.py)